# A short, descriptive name of this building block collection
name: GeoPose

# Short abstract for this collection (optional)
abstract: |
  [GeoPose](https://www.geopose.org/) Building Blocks

# Description for this collection (optional)
#description: |
#  The description can be longer. Both **the abstract** *and the description* support Markdown,
#  including [links](https://google.es).

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.geo.geopose.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default

# Whether to enable the (highly experimental) downcompiling of JSON schemas to an OpenAPI 3.0-compatible
# version
schema-oas30-downcompile: False

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
#   resources:                              # Additional resources to upload apart from building block metadata
#      ontologies: true                     #   Whether to upload ontology files to the triplestore